apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: pineapple
    name: pineapple
  name: pineapple
spec:
  replicas: 1
  selector:
    app: pineapple
    deploymentconfig: pineapple
    name: pineapple
  strategy:
    resources: {}
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
        sidecar.istio.io/inject: 'true'
      creationTimestamp: null
      labels:
        app: pineapple
        deploymentconfig: pineapple
        name: pineapple
    spec:
      containers:
      - image: sample-nodejs:latest
        name: pineapple
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - pineapple
      from:
        kind: ImageStreamTag
        name: sample-nodejs:latest
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: pineapple
    name: pineapple
  name: pineapple
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pineapple
    deploymentconfig: pineapple
    name: pineapple
status:
  loadBalancer: {}